# Generated by Django 5.2.17 on 2026-10-03 04:41

from collections import Counter

from django.db import migrations, models
from django.utils import timezone


def count_live_guest_sessions(apps, schema_editor):
    """Book guest sessions that still exist at deploy time as started.

    Sessions deleted before this migration left no trace and cannot be
    recovered.
    """
    GuestDemoSession = apps.get_model("accounts", "GuestDemoSession")
    GuestDemoUsageDay = apps.get_model("accounts", "GuestDemoUsageDay")
    started_per_day = Counter(
        timezone.localdate(created_at)
        for created_at in GuestDemoSession.objects.values_list("created_at", flat=True)
    )
    GuestDemoUsageDay.objects.bulk_create(
        GuestDemoUsageDay(date=day, started=count) for day, count in started_per_day.items()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_accounttrustprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestDemoUsageDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "started",
                    models.PositiveIntegerField(
                        default=0, help_text="Guest demo sessions started on this day."
                    ),
                ),
                (
                    "used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Guest demo sessions started on this day that had at least one user change when they were deleted.",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.RunPython(count_live_guest_sessions, migrations.RunPython.noop),
    ]
