# Generated by Django 5.2.17 on 2026-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_public_culture_notification_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('crop_species_proposal_accepted', 'Crop species proposal accepted'), ('crop_species_proposal_rejected', 'Crop species proposal rejected'), ('crop_species_proposal_submitted', 'Crop species proposal submitted'), ('moderator_request_submitted', 'Moderator request submitted'), ('public_crop_removed', 'Public crop removed'), ('public_crop_change_proposal_submitted', 'Public crop change proposal submitted'), ('public_crop_change_proposal_reviewed', 'Public crop change proposal reviewed')], max_length=64),
        ),
    ]
