# Generated by Django 5.2.17 on 2026-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    (
                        "crop_species_proposal_accepted",
                        "Crop species proposal accepted",
                    ),
                    (
                        "crop_species_proposal_rejected",
                        "Crop species proposal rejected",
                    ),
                    (
                        "crop_species_proposal_submitted",
                        "Crop species proposal submitted",
                    ),
                    ("moderator_request_submitted", "Moderator request submitted"),
                    ("public_crop_removed", "Public crop removed"),
                    (
                        "public_crop_species_relink_cancelled",
                        "Public crop species correction cancelled",
                    ),
                    ("crop_species_reassigned", "Crop species reassigned"),
                    (
                        "public_crop_change_proposal_submitted",
                        "Public crop change proposal submitted",
                    ),
                    (
                        "public_crop_change_proposal_reviewed",
                        "Public crop change proposal reviewed",
                    ),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("crop", "Project crop"),
                    ("public_crop", "Public crop"),
                    ("crop_species", "Crop species"),
                    ("public_library_moderation", "Public library moderation queue"),
                ],
                max_length=32,
            ),
        ),
    ]
