"""Central seed data for official crop-library species."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CropSpeciesSeedEntry:
    """Language-independent species entry prepared for later translations."""

    key: str
    translations: dict[str, str]
    scientific_name: str = ''
    family: str = ''
    categories: tuple[str, ...] = ()


CROP_SPECIES_SEED_DATA: tuple[CropSpeciesSeedEntry, ...] = (
    CropSpeciesSeedEntry(key='alfalfa', translations={'de': 'Luzerne', 'en': 'Alfalfa'}),
    CropSpeciesSeedEntry(key='alexandrian_clover', translations={'de': 'Alexandrinerklee', 'en': 'Alexandrian clover'}),
    CropSpeciesSeedEntry(key='amaranth', translations={'de': 'Amaranth', 'en': 'Amaranth'}),
    CropSpeciesSeedEntry(key='ammi', translations={'de': 'Bischofskraut', 'en': 'Ammi'}),
    CropSpeciesSeedEntry(key='anise', translations={'de': 'Anis', 'en': 'Anise'}),
    CropSpeciesSeedEntry(key='apple', translations={'de': 'Apfel', 'en': 'Apple'}),
    CropSpeciesSeedEntry(key='apricot', translations={'de': 'Marille', 'en': 'Apricot'}),
    CropSpeciesSeedEntry(key='artichoke', translations={'de': 'Artischocke', 'en': 'Artichoke'}),
    CropSpeciesSeedEntry(key='asparagus', translations={'de': 'Spargel', 'en': 'Asparagus'}),
    CropSpeciesSeedEntry(key='aubergine', translations={'de': 'Aubergine', 'en': 'Eggplant'}),
    CropSpeciesSeedEntry(key='barley', translations={'de': 'Gerste', 'en': 'Barley'}),
    CropSpeciesSeedEntry(key='basil', translations={'de': 'Basilikum', 'en': 'Basil'}),
    CropSpeciesSeedEntry(key='beetroot', translations={'de': 'Rote Rübe', 'en': 'Beetroot'}),
    CropSpeciesSeedEntry(key='black_salsify', translations={'de': 'Schwarzwurzel', 'en': 'Black salsify'}),
    CropSpeciesSeedEntry(key='blackcurrant', translations={'de': 'Schwarze Ribisel', 'en': 'Blackcurrant'}),
    CropSpeciesSeedEntry(key='blackberry', translations={'de': 'Brombeere', 'en': 'Blackberry'}),
    CropSpeciesSeedEntry(key='blueberry', translations={'de': 'Heidelbeere', 'en': 'Blueberry'}),
    CropSpeciesSeedEntry(key='borage', translations={'de': 'Borretsch', 'en': 'Borage'}),
    CropSpeciesSeedEntry(key='broad_bean', translations={'de': 'Ackerbohne', 'en': 'Broad bean'}),
    CropSpeciesSeedEntry(key='broccoli', translations={'de': 'Brokkoli', 'en': 'Broccoli'}),
    CropSpeciesSeedEntry(key='brussels_sprout', translations={'de': 'Rosenkohl', 'en': 'Brussels sprout'}),
    CropSpeciesSeedEntry(key='buckwheat', translations={'de': 'Buchweizen', 'en': 'Buckwheat'}),
    CropSpeciesSeedEntry(key='bush_bean', translations={'de': 'Buschbohne', 'en': 'Bush bean'}),
    CropSpeciesSeedEntry(key='cabbage', translations={'de': 'Weißkraut', 'en': 'White cabbage'}),
    CropSpeciesSeedEntry(key='camelina', translations={'de': 'Leindotter', 'en': 'Camelina'}),
    CropSpeciesSeedEntry(key='canola', translations={'de': 'Raps', 'en': 'Canola'}),
    CropSpeciesSeedEntry(key='calendula', translations={'de': 'Ringelblume', 'en': 'Calendula'}),
    CropSpeciesSeedEntry(key='caraway', translations={'de': 'Kümmel', 'en': 'Caraway'}),
    CropSpeciesSeedEntry(key='cardoon', translations={'de': 'Kardy', 'en': 'Cardoon'}),
    CropSpeciesSeedEntry(key='carrot', translations={'de': 'Karotte', 'en': 'Carrot'}),
    CropSpeciesSeedEntry(key='cauliflower', translations={'de': 'Karfiol', 'en': 'Cauliflower'}),
    CropSpeciesSeedEntry(key='celeriac', translations={'de': 'Knollensellerie', 'en': 'Celeriac'}),
    CropSpeciesSeedEntry(key='celery', translations={'de': 'Stangensellerie', 'en': 'Celery'}),
    CropSpeciesSeedEntry(key='chamomile', translations={'de': 'Kamille', 'en': 'Chamomile'}),
    CropSpeciesSeedEntry(key='chard', translations={'de': 'Mangold', 'en': 'Chard'}),
    CropSpeciesSeedEntry(key='cherry', translations={'de': 'Kirsche', 'en': 'Cherry'}),
    CropSpeciesSeedEntry(key='chestnut', translations={'de': 'Edelkastanie', 'en': 'Chestnut'}),
    CropSpeciesSeedEntry(key='chervil', translations={'de': 'Kerbel', 'en': 'Chervil'}),
    CropSpeciesSeedEntry(key='chickpea', translations={'de': 'Kichererbse', 'en': 'Chickpea'}),
    CropSpeciesSeedEntry(key='chinese_cabbage', translations={'de': 'Chinakohl', 'en': 'Chinese cabbage'}),
    CropSpeciesSeedEntry(key='chicory', translations={'de': 'Chicorée', 'en': 'Chicory'}),
    CropSpeciesSeedEntry(key='chili', translations={'de': 'Chili', 'en': 'Chili pepper'}),
    CropSpeciesSeedEntry(key='chives', translations={'de': 'Schnittlauch', 'en': 'Chives'}),
    CropSpeciesSeedEntry(key='cima_di_rapa', translations={'de': 'Stängelkohl', 'en': 'Broccoli raab'}),
    CropSpeciesSeedEntry(key='common_vetch', translations={'de': 'Saatwicke', 'en': 'Common vetch'}),
    CropSpeciesSeedEntry(key='cornflower', translations={'de': 'Kornblume', 'en': 'Cornflower'}),
    CropSpeciesSeedEntry(key='coriander', translations={'de': 'Koriander', 'en': 'Coriander'}),
    CropSpeciesSeedEntry(key='corn_salad', translations={'de': 'Feldsalat', 'en': 'Corn salad'}),
    CropSpeciesSeedEntry(key='cosmos', translations={'de': 'Schmuckkörbchen', 'en': 'Cosmos'}),
    CropSpeciesSeedEntry(key='cress', translations={'de': 'Kresse', 'en': 'Cress'}),
    CropSpeciesSeedEntry(key='crimson_clover', translations={'de': 'Inkarnatklee', 'en': 'Crimson clover'}),
    CropSpeciesSeedEntry(key='cucumber', translations={'de': 'Gurke', 'en': 'Cucumber'}),
    CropSpeciesSeedEntry(key='currant', translations={'de': 'Ribisel', 'en': 'Currant'}),
    CropSpeciesSeedEntry(key='daikon', translations={'de': 'Rettich', 'en': 'Daikon radish'}),
    CropSpeciesSeedEntry(key='dill', translations={'de': 'Dill', 'en': 'Dill'}),
    CropSpeciesSeedEntry(key='durum_wheat', translations={'de': 'Hartweizen', 'en': 'Durum wheat'}),
    CropSpeciesSeedEntry(key='einkorn', translations={'de': 'Einkorn', 'en': 'Einkorn'}),
    CropSpeciesSeedEntry(key='elderberry', translations={'de': 'Holunder', 'en': 'Elderberry'}),
    CropSpeciesSeedEntry(key='emmer', translations={'de': 'Emmer', 'en': 'Emmer'}),
    CropSpeciesSeedEntry(key='endive', translations={'de': 'Endivie', 'en': 'Endive'}),
    CropSpeciesSeedEntry(
        key='fennel_bulb',
        translations={'de': 'Knollenfenchel', 'en': 'Florence fennel'},
        scientific_name='Foeniculum vulgare var. azoricum',
        family='Apiaceae',
        categories=('vegetable',),
    ),
    CropSpeciesSeedEntry(
        key='fennel_herb',
        translations={'de': 'Gewürzfenchel', 'en': 'Common fennel'},
        scientific_name='Foeniculum vulgare',
        family='Apiaceae',
        categories=('herb',),
    ),
    CropSpeciesSeedEntry(key='field_pea', translations={'de': 'Futtererbse', 'en': 'Field pea'}),
    CropSpeciesSeedEntry(key='flax', translations={'de': 'Lein', 'en': 'Flax'}),
    CropSpeciesSeedEntry(key='fodder_beet', translations={'de': 'Futterrübe', 'en': 'Fodder beet'}),
    CropSpeciesSeedEntry(key='french_bean', translations={'de': 'Grüne Bohne', 'en': 'French bean'}),
    CropSpeciesSeedEntry(key='garden_orach', translations={'de': 'Gartenmelde', 'en': 'Garden orach'}),
    CropSpeciesSeedEntry(key='garden_rocket', translations={'de': 'Salatrauke', 'en': 'Garden rocket'}),
    CropSpeciesSeedEntry(key='garlic', translations={'de': 'Knoblauch', 'en': 'Garlic'}),
    CropSpeciesSeedEntry(key='gooseberry', translations={'de': 'Stachelbeere', 'en': 'Gooseberry'}),
    CropSpeciesSeedEntry(key='grape', translations={'de': 'Weintraube', 'en': 'Grape'}),
    CropSpeciesSeedEntry(key='hazelnut', translations={'de': 'Haselnuss', 'en': 'Hazelnut'}),
    CropSpeciesSeedEntry(key='hemp', translations={'de': 'Hanf', 'en': 'Hemp'}),
    CropSpeciesSeedEntry(key='hop', translations={'de': 'Hopfen', 'en': 'Hop'}),
    CropSpeciesSeedEntry(key='horseradish', translations={'de': 'Kren', 'en': 'Horseradish'}),
    CropSpeciesSeedEntry(key='hyssop', translations={'de': 'Ysop', 'en': 'Hyssop'}),
    CropSpeciesSeedEntry(key='iceberg_lettuce', translations={'de': 'Eisbergsalat', 'en': 'Iceberg lettuce'}),
    CropSpeciesSeedEntry(key='jerusalem_artichoke', translations={'de': 'Topinambur', 'en': 'Jerusalem artichoke'}),
    CropSpeciesSeedEntry(key='kale', translations={'de': 'Grünkohl', 'en': 'Kale'}),
    CropSpeciesSeedEntry(key='kidney_bean', translations={'de': 'Kidneybohne', 'en': 'Kidney bean'}),
    CropSpeciesSeedEntry(key='kiwi', translations={'de': 'Kiwi', 'en': 'Kiwi'}),
    CropSpeciesSeedEntry(key='kohlrabi', translations={'de': 'Kohlrabi', 'en': 'Kohlrabi'}),
    CropSpeciesSeedEntry(key='komatsuna', translations={'de': 'Komatsuna', 'en': 'Komatsuna'}),
    CropSpeciesSeedEntry(key='lavender', translations={'de': 'Lavendel', 'en': 'Lavender'}),
    CropSpeciesSeedEntry(
        key='leaf_cabbage',
        translations={'de': 'Schnittkohl', 'en': 'Cutting cabbage'},
        scientific_name='Brassica oleracea var. viridis',
        family='Brassicaceae',
        categories=('vegetable',),
    ),
    CropSpeciesSeedEntry(
        key='leaf_mustard',
        translations={'de': 'Blattsenf', 'en': 'Mustard greens'},
        scientific_name='Brassica juncea',
        family='Brassicaceae',
        categories=('vegetable',),
    ),
    CropSpeciesSeedEntry(key='leek', translations={'de': 'Lauch', 'en': 'Leek'}),
    CropSpeciesSeedEntry(key='lemon_balm', translations={'de': 'Zitronenmelisse', 'en': 'Lemon balm'}),
    CropSpeciesSeedEntry(key='lentil', translations={'de': 'Linse', 'en': 'Lentil'}),
    CropSpeciesSeedEntry(key='lettuce', translations={'de': 'Salat', 'en': 'Lettuce'}),
    CropSpeciesSeedEntry(key='lovage', translations={'de': 'Liebstöckel', 'en': 'Lovage'}),
    CropSpeciesSeedEntry(key='lupin', translations={'de': 'Lupine', 'en': 'Lupin'}),
    CropSpeciesSeedEntry(key='maize', translations={'de': 'Mais', 'en': 'Maize'}),
    CropSpeciesSeedEntry(key='mallow', translations={'de': 'Malve', 'en': 'Mallow'}),
    CropSpeciesSeedEntry(key='marigold', translations={'de': 'Tagetes', 'en': 'Marigold'}),
    CropSpeciesSeedEntry(key='marjoram', translations={'de': 'Majoran', 'en': 'Marjoram'}),
    CropSpeciesSeedEntry(key='medlar', translations={'de': 'Mispel', 'en': 'Medlar'}),
    CropSpeciesSeedEntry(key='melon', translations={'de': 'Melone', 'en': 'Melon'}),
    CropSpeciesSeedEntry(key='mibuna', translations={'de': 'Mibuna', 'en': 'Mibuna'}),
    CropSpeciesSeedEntry(key='mint', translations={'de': 'Minze', 'en': 'Mint'}),
    CropSpeciesSeedEntry(key='mizuna', translations={'de': 'Mizuna', 'en': 'Mizuna'}),
    CropSpeciesSeedEntry(key='mung_bean', translations={'de': 'Mungbohne', 'en': 'Mung bean'}),
    CropSpeciesSeedEntry(key='mustard', translations={'de': 'Senf', 'en': 'Mustard'}),
    CropSpeciesSeedEntry(key='nasturtium', translations={'de': 'Kapuzinerkresse', 'en': 'Nasturtium'}),
    CropSpeciesSeedEntry(key='nectarine', translations={'de': 'Nektarine', 'en': 'Nectarine'}),
    CropSpeciesSeedEntry(key='new_zealand_spinach', translations={'de': 'Neuseeländer Spinat', 'en': 'New Zealand spinach'}),
    CropSpeciesSeedEntry(key='nigella', translations={'de': 'Jungfer im Grünen', 'en': 'Nigella'}),
    CropSpeciesSeedEntry(key='oat', translations={'de': 'Hafer', 'en': 'Oat'}),
    CropSpeciesSeedEntry(key='oil_radish', translations={'de': 'Ölrettich', 'en': 'Oil radish'}),
    CropSpeciesSeedEntry(key='okra', translations={'de': 'Okra', 'en': 'Okra'}),
    CropSpeciesSeedEntry(key='onion', translations={'de': 'Zwiebel', 'en': 'Onion'}),
    CropSpeciesSeedEntry(key='oregano', translations={'de': 'Oregano', 'en': 'Oregano'}),
    CropSpeciesSeedEntry(key='pak_choi', translations={'de': 'Pak Choi', 'en': 'Pak choi'}),
    CropSpeciesSeedEntry(key='parsley_root', translations={'de': 'Wurzelpetersilie', 'en': 'Parsley root'}),
    CropSpeciesSeedEntry(key='parsley', translations={'de': 'Petersilie', 'en': 'Parsley'}),
    CropSpeciesSeedEntry(key='parsnip', translations={'de': 'Pastinake', 'en': 'Parsnip'}),
    CropSpeciesSeedEntry(key='pattypan_squash', translations={'de': 'Patisson', 'en': 'Pattypan squash'}),
    CropSpeciesSeedEntry(key='peach', translations={'de': 'Pfirsich', 'en': 'Peach'}),
    CropSpeciesSeedEntry(key='peanut', translations={'de': 'Erdnuss', 'en': 'Peanut'}),
    CropSpeciesSeedEntry(key='pea', translations={'de': 'Erbse', 'en': 'Pea'}),
    CropSpeciesSeedEntry(key='pear', translations={'de': 'Birne', 'en': 'Pear'}),
    CropSpeciesSeedEntry(key='pepper', translations={'de': 'Paprika', 'en': 'Sweet pepper'}),
    CropSpeciesSeedEntry(key='perilla', translations={'de': 'Shiso', 'en': 'Perilla'}),
    CropSpeciesSeedEntry(
        key='pepperoncini',
        translations={'de': 'Pfefferoni', 'en': 'Pepperoncini'},
        scientific_name='Capsicum annuum',
        family='Solanaceae',
        categories=('vegetable',),
    ),
    CropSpeciesSeedEntry(key='persian_clover', translations={'de': 'Perserklee', 'en': 'Persian clover'}),
    CropSpeciesSeedEntry(key='phacelia', translations={'de': 'Phacelia', 'en': 'Phacelia'}),
    CropSpeciesSeedEntry(key='physalis', translations={'de': 'Physalis', 'en': 'Physalis'}),
    CropSpeciesSeedEntry(key='pole_bean', translations={'de': 'Stangenbohne', 'en': 'Pole bean'}),
    CropSpeciesSeedEntry(key='plum', translations={'de': 'Zwetschke', 'en': 'Plum'}),
    CropSpeciesSeedEntry(key='poppy', translations={'de': 'Mohn', 'en': 'Poppy'}),
    CropSpeciesSeedEntry(key='potato', translations={'de': 'Kartoffel', 'en': 'Potato'}),
    CropSpeciesSeedEntry(key='pumpkin', translations={'de': 'Kürbis', 'en': 'Pumpkin'}),
    CropSpeciesSeedEntry(
        key='puntarelle',
        translations={'de': 'Puntarelle', 'en': 'Puntarelle'},
        scientific_name='Cichorium intybus var. foliosum',
        family='Asteraceae',
        categories=('vegetable',),
    ),
    CropSpeciesSeedEntry(key='purslane', translations={'de': 'Portulak', 'en': 'Purslane'}),
    CropSpeciesSeedEntry(key='quince', translations={'de': 'Quitte', 'en': 'Quince'}),
    CropSpeciesSeedEntry(key='quinoa', translations={'de': 'Quinoa', 'en': 'Quinoa'}),
    CropSpeciesSeedEntry(key='radicchio', translations={'de': 'Radicchio', 'en': 'Radicchio'}),
    CropSpeciesSeedEntry(key='radish', translations={'de': 'Radieschen', 'en': 'Radish'}),
    CropSpeciesSeedEntry(key='ramson', translations={'de': 'Bärlauch', 'en': 'Ramson'}),
    CropSpeciesSeedEntry(key='raspberry', translations={'de': 'Himbeere', 'en': 'Raspberry'}),
    CropSpeciesSeedEntry(key='red_cabbage', translations={'de': 'Rotkraut', 'en': 'Red cabbage'}),
    CropSpeciesSeedEntry(key='red_clover', translations={'de': 'Rotklee', 'en': 'Red clover'}),
    CropSpeciesSeedEntry(key='rhubarb', translations={'de': 'Rhabarber', 'en': 'Rhubarb'}),
    CropSpeciesSeedEntry(key='romaine_lettuce', translations={'de': 'Römersalat', 'en': 'Romaine lettuce'}),
    CropSpeciesSeedEntry(key='rosemary', translations={'de': 'Rosmarin', 'en': 'Rosemary'}),
    CropSpeciesSeedEntry(key='rocket', translations={'de': 'Rucola', 'en': 'Rocket'}),
    CropSpeciesSeedEntry(key='runner_bean', translations={'de': 'Feuerbohne', 'en': 'Runner bean'}),
    CropSpeciesSeedEntry(key='rye', translations={'de': 'Roggen', 'en': 'Rye'}),
    CropSpeciesSeedEntry(key='sage', translations={'de': 'Salbei', 'en': 'Sage'}),
    CropSpeciesSeedEntry(key='savory', translations={'de': 'Bohnenkraut', 'en': 'Savory'}),
    CropSpeciesSeedEntry(key='savoy_cabbage', translations={'de': 'Wirsing', 'en': 'Savoy cabbage'}),
    CropSpeciesSeedEntry(key='scabiosa', translations={'de': 'Skabiose', 'en': 'Scabiosa'}),
    CropSpeciesSeedEntry(key='sea_buckthorn', translations={'de': 'Sanddorn', 'en': 'Sea buckthorn'}),
    CropSpeciesSeedEntry(key='serradella', translations={'de': 'Serradella', 'en': 'Serradella'}),
    CropSpeciesSeedEntry(key='shallot', translations={'de': 'Schalotte', 'en': 'Shallot'}),
    CropSpeciesSeedEntry(key='snapdragon', translations={'de': 'Löwenmäulchen', 'en': 'Snapdragon'}),
    CropSpeciesSeedEntry(key='sorghum', translations={'de': 'Sorghum', 'en': 'Sorghum'}),
    CropSpeciesSeedEntry(key='sorrel', translations={'de': 'Sauerampfer', 'en': 'Sorrel'}),
    CropSpeciesSeedEntry(key='soybean', translations={'de': 'Sojabohne', 'en': 'Soybean'}),
    CropSpeciesSeedEntry(key='spinach', translations={'de': 'Spinat', 'en': 'Spinach'}),
    CropSpeciesSeedEntry(key='spelt', translations={'de': 'Dinkel', 'en': 'Spelt'}),
    CropSpeciesSeedEntry(key='pointed_cabbage', translations={'de': 'Spitzkraut', 'en': 'Pointed cabbage'}),
    CropSpeciesSeedEntry(key='spring_onion', translations={'de': 'Frühlingszwiebel', 'en': 'Spring onion'}),
    CropSpeciesSeedEntry(key='strawberry', translations={'de': 'Erdbeere', 'en': 'Strawberry'}),
    CropSpeciesSeedEntry(key='strawflower', translations={'de': 'Strohblume', 'en': 'Strawflower'}),
    CropSpeciesSeedEntry(key='sugar_beet', translations={'de': 'Zuckerrübe', 'en': 'Sugar beet'}),
    CropSpeciesSeedEntry(
        key='sugar_pea',
        translations={'de': 'Zuckererbse', 'en': 'Sugar pea'},
        scientific_name='Pisum sativum var. saccharatum',
        family='Fabaceae',
        categories=('vegetable',),
    ),
    CropSpeciesSeedEntry(key='sugarloaf_chicory', translations={'de': 'Zuckerhut', 'en': 'Sugarloaf chicory'}),
    CropSpeciesSeedEntry(key='sunflower', translations={'de': 'Sonnenblume', 'en': 'Sunflower'}),
    CropSpeciesSeedEntry(key='summer_squash', translations={'de': 'Zucchini', 'en': 'Zucchini'}),
    CropSpeciesSeedEntry(key='sweet_potato', translations={'de': 'Süßkartoffel', 'en': 'Sweet potato'}),
    CropSpeciesSeedEntry(key='sweet_pea', translations={'de': 'Duftwicke', 'en': 'Sweet pea'}),
    CropSpeciesSeedEntry(key='sweetcorn', translations={'de': 'Zuckermais', 'en': 'Sweetcorn'}),
    CropSpeciesSeedEntry(key='tarragon', translations={'de': 'Estragon', 'en': 'Tarragon'}),
    CropSpeciesSeedEntry(key='tatsoi', translations={'de': 'Tatsoi', 'en': 'Tatsoi'}),
    CropSpeciesSeedEntry(key='thyme', translations={'de': 'Thymian', 'en': 'Thyme'}),
    CropSpeciesSeedEntry(key='tomato', translations={'de': 'Tomate', 'en': 'Tomato'}),
    CropSpeciesSeedEntry(key='triticale', translations={'de': 'Triticale', 'en': 'Triticale'}),
    CropSpeciesSeedEntry(key='turnip', translations={'de': 'Speiserübe', 'en': 'Turnip'}),
    CropSpeciesSeedEntry(key='watercress', translations={'de': 'Brunnenkresse', 'en': 'Watercress'}),
    CropSpeciesSeedEntry(key='walnut', translations={'de': 'Walnuss', 'en': 'Walnut'}),
    CropSpeciesSeedEntry(key='watermelon', translations={'de': 'Wassermelone', 'en': 'Watermelon'}),
    CropSpeciesSeedEntry(key='wheat', translations={'de': 'Weizen', 'en': 'Wheat'}),
    CropSpeciesSeedEntry(key='white_clover', translations={'de': 'Weißklee', 'en': 'White clover'}),
    CropSpeciesSeedEntry(key='wild_rocket', translations={'de': 'Wilde Rauke', 'en': 'Wild rocket'}),
    CropSpeciesSeedEntry(key='winter_cress', translations={'de': 'Winterkresse', 'en': 'Winter cress'}),
    CropSpeciesSeedEntry(key='winter_purslane', translations={'de': 'Winterportulak', 'en': 'Winter purslane'}),
    CropSpeciesSeedEntry(key='zinnia', translations={'de': 'Zinnie', 'en': 'Zinnia'}),
)


def get_crop_species_seed_name(entry: CropSpeciesSeedEntry, language_code: str = 'de') -> str:
    """Return the best display name currently supported by the species model."""
    return entry.translations.get(language_code) or entry.translations['de']


# Search-only aliases (regional and colloquial names) per seed key and
# language. An alias never becomes its own species: it resolves to the
# canonical species in autocomplete, search, and duplicate detection, which is
# what keeps "Erdapfel" from being published as a second Kartoffel.
#
# What may become an alias is a naming question, not a botanical one: a term
# is an alias only when it names the *same product* under a regional or
# colloquial name — same growing time, same cultivation, same plant part, same
# harvest method (Erdapfel/Kartoffel, Karfiol/Blumenkohl, Porree/Lauch). A
# functionally different use form stays its own species even when it is
# botanically the same species: Pfefferoni is not an alias of Paprika
# (different growing time and spacing, and users search for it deliberately),
# Radicchio and Puntarelle stay separate from the other chicories, Schnittkohl
# stays separate from Grünkohl because it is cut repeatedly as young leaves
# instead of harvested once as a whole plant, and Zuckererbse stays separate
# from Erbse because it is harvested and eaten pod and all.
#
# Deliberately ambiguous terms are mapped onto *several* species so the UI can
# offer all of them instead of silently picking one:
#   - "Peperoni" is the sweet pepper in CH, the hot chili in DE/AT, and the
#     Pfefferoni in everyday use.
#   - "Fisole(n)" (AT) covers every green bean — bush, pole, and French bean,
#     which stay separate species because their cultivation differs.
# "Kohlrübe" is deliberately absent: it names the swede (Brassica napus), a
# species of its own that the library does not seed yet — aliasing it onto
# Kohlrabi would merge two different crops.
CROP_SPECIES_SYNONYM_SEED_DATA: dict[str, dict[str, tuple[str, ...]]] = {
    'apricot': {'de': ('Aprikose',)},
    'beetroot': {'de': ('Rote Bete', 'Rande', 'Randen')},
    'black_salsify': {'de': ('Winterspargel',)},
    'blackcurrant': {'de': ('Schwarze Johannisbeere',)},
    'blueberry': {'de': ('Blaubeere', 'Schwarzbeere')},
    'broad_bean': {'de': ('Saubohne', 'Puffbohne', 'Dicke Bohne', 'Favabohne')},
    'brussels_sprout': {'de': ('Kohlsprossen', 'Sprossenkohl')},
    'bush_bean': {'de': ('Fisole', 'Fisolen')},
    'cabbage': {'de': ('Weißkohl', 'Kabis')},
    'caraway': {'de': ('Wiesenkümmel',)},
    'carrot': {'de': ('Möhre', 'Mohrrübe', 'Gelbe Rübe', 'Rüebli')},
    'cauliflower': {'de': ('Blumenkohl', 'Blumenkabis')},
    'celeriac': {'de': ('Sellerieknolle', 'Zeller')},
    'celery': {'de': ('Staudensellerie', 'Bleichsellerie')},
    'chard': {'de': ('Krautstiel', 'Stielmangold')},
    'chicory': {'de': ('Brüsseler Endivie', 'Chicoree')},
    'chili': {'de': ('Chilischote', 'Chilli', 'Peperoni')},
    'chinese_cabbage': {'de': ('Pekingkohl',)},
    'chives': {'de': ('Schnittling',)},
    'corn_salad': {'de': ('Vogerlsalat', 'Nüsslisalat', 'Ackersalat', 'Rapunzel')},
    'currant': {'de': ('Johannisbeere',)},
    'daikon': {'de': ('Winterrettich', 'Radi')},
    'elderberry': {'de': ('Holler', 'Fliederbeere')},
    'endive': {'de': ('Winterendivie', 'Escariol')},
    'french_bean': {'de': ('Fisole', 'Fisolen')},
    'garden_orach': {'de': ('Melde',)},
    'gooseberry': {'de': ('Agrasel',)},
    'horseradish': {'de': ('Meerrettich',)},
    'iceberg_lettuce': {'de': ('Eissalat', 'Krachsalat')},
    'jerusalem_artichoke': {'de': ('Erdbirne', 'Erdartischocke')},
    'kale': {'de': ('Federkohl', 'Braunkohl')},
    'leek': {'de': ('Porree', 'Breitlauch')},
    'lettuce': {'de': ('Kopfsalat', 'Häuptlsalat')},
    'lovage': {'de': ('Maggikraut',)},
    'maize': {'de': ('Kukuruz',)},
    'marjoram': {'de': ('Meiran',)},
    'parsley': {'de': ('Petersil',)},
    'parsley_root': {'de': ('Petersilienwurzel',)},
    'pepper': {'de': ('Gemüsepaprika', 'Paprikaschote', 'Peperoni')},
    'pepperoncini': {'de': ('Peperoni', 'Peperoncini', 'Spitzpaprika')},
    'plum': {'de': ('Zwetschge', 'Pflaume')},
    'pointed_cabbage': {'de': ('Spitzkohl',)},
    'pole_bean': {'de': ('Fisole', 'Fisolen', 'Stangenfisolen')},
    'potato': {'de': ('Erdapfel', 'Erdäpfel', 'Grundbirne')},
    'purslane': {'de': ('Sommerportulak', 'Burzelkraut')},
    'ramson': {'de': ('Waldknoblauch', 'Wilder Knoblauch')},
    'red_cabbage': {'de': ('Rotkohl', 'Blaukraut')},
    'romaine_lettuce': {'de': ('Romanasalat', 'Bindesalat', 'Kochsalat')},
    'savoy_cabbage': {'de': ('Wirsingkohl', 'Wirz')},
    'spring_onion': {'de': ('Lauchzwiebel', 'Jungzwiebel', 'Winterzwiebel')},
    'sugar_pea': {'de': ('Zuckerschote', 'Kaiserschote', 'Kefe')},
    'sugarloaf_chicory': {'de': ('Fleischkraut',)},
    'summer_squash': {'de': ('Zucchetti', 'Zucchino')},
    'sweetcorn': {'de': ('Süßmais', 'Zuckerkukuruz')},
    'tomato': {'de': ('Paradeiser', 'Paradeis')},
    'turnip': {'de': ('Mairübe', 'Herbstrübe', 'Navette')},
    'winter_purslane': {'de': ('Postelein', 'Tellerkraut', 'Kubaspinat')},
}


def get_crop_species_seed_synonyms(key: str, language_code: str = 'de') -> tuple[str, ...]:
    """Search aliases seeded for one species in one language."""
    return CROP_SPECIES_SYNONYM_SEED_DATA.get(key, {}).get(language_code, ())
