from __future__ import annotations

# Curated list of common disposable/throwaway email providers. Not exhaustive
# by design: the point is to raise the cost of casual mass-registration abuse,
# not to guarantee every disposable domain is caught.
DISPOSABLE_EMAIL_DOMAINS: frozenset[str] = frozenset(
    {
        '0-mail.com',
        '0815.ru',
        '10minutemail.com',
        '10minutemail.net',
        '20minutemail.com',
        '33mail.com',
        'anonaddy.com',
        'armyspy.com',
        'burnermail.io',
        'byom.de',
        'cs.email',
        'deadaddress.com',
        'despam.it',
        'dispostable.com',
        'dropmail.me',
        'einrot.com',
        'emailondeck.com',
        'emailtemporario.com.br',
        'fakeinbox.com',
        'fakemailgenerator.com',
        'getairmail.com',
        'getnada.com',
        'grr.la',
        'guerrillamail.biz',
        'guerrillamail.com',
        'guerrillamail.de',
        'guerrillamail.net',
        'guerrillamail.org',
        'guerrillamailblock.com',
        'harakirimail.com',
        'inboxbear.com',
        'jetable.org',
        'mail-temporaire.fr',
        'mail-temporaire.net',
        'mailcatch.com',
        'mailde.de',
        'mailinator.com',
        'mailinator.net',
        'mailnesia.com',
        'maildrop.cc',
        'mailsac.com',
        'meltmail.com',
        'mintemail.com',
        'moakt.com',
        'mohmal.com',
        'mt2015.com',
        'mytemp.email',
        'nada.email',
        'nomail.xl.cx',
        'nwytg.com',
        'owlymail.com',
        'sharklasers.com',
        'spam4.me',
        'spamavert.com',
        'spambog.com',
        'spambox.us',
        'spamgourmet.com',
        'spamherelots.com',
        'spamthisplease.com',
        'superrito.com',
        'tempail.com',
        'tempinbox.com',
        'tempmail.com',
        'tempmail.net',
        'tempmail2.com',
        'temp-mail.org',
        'temp-mail.ru',
        'temporary-mail.net',
        'temporaryemail.us',
        'thankyou2010.com',
        'throwawaymail.com',
        'tmail.ws',
        'tmailinator.com',
        'trash-mail.com',
        'trashmail.com',
        'trashmail.net',
        'trbvm.com',
        'wegwerfemail.de',
        'wegwerfmail.de',
        'wegwerfmail.net',
        'wegwerfmail.org',
        'yopmail.com',
        'yopmail.fr',
        'yopmail.net',
        'zoemail.com',
    },
)


def is_disposable_email_domain(email: str) -> bool:
    """Return whether the email's domain is a known disposable-mail provider."""
    domain = email.rsplit('@', 1)[-1].strip().lower()
    return domain in DISPOSABLE_EMAIL_DOMAINS
