# Generated by Django 5.2.17 on 2026-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0104_mediafile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccropchangeproposal',
            name='kind',
            field=models.CharField(choices=[('edit', 'Edit'), ('new_publish', 'New publish')], default='edit', max_length=20),
        ),
        migrations.AddField(
            model_name='publiccropchangeproposal',
            name='origin_api',
            field=models.BooleanField(default=False, help_text='Whether this proposal was created through a ProjectApiToken-authenticated request.'),
        ),
        migrations.AddField(
            model_name='publiccropchangeproposal',
            name='origin_declared_agent',
            field=models.BooleanField(default=False, help_text='Whether the request self-declared as an automated/agent client (X-Client-Declared-Type).'),
        ),
    ]
