# Generated by Django 5.2.17 on 2026-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0105_publiccropchangeproposal_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccrop',
            name='removal_reason',
            field=models.CharField(blank=True, choices=[('accidental_publication', 'Accidental publication'), ('test_data', 'Test data'), ('duplicate', 'Duplicate'), ('wrong_mapping', 'Wrong mapping'), ('unlawful_content', 'Unlawful content'), ('species_rejected', 'Crop species rejected'), ('proposal_rejected', 'New-publish proposal rejected'), ('other', 'Other')], max_length=50),
        ),
    ]
