# Generated by Django 5.2.17 on 2026-09-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0015_crop_species_regional_display_names"),
        ("farm", "0106_alter_publiccrop_removal_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="publiccroprevision",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("restored", "Restored"),
                    ("species_relinked", "Crop species relinked"),
                ],
                default="updated",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PublicCropSpeciesRelinkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_crop_species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_crop_relinks_away",
                        to="crops.cropspecies",
                    ),
                ),
                (
                    "public_crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_relink_requests",
                        to="farm.publiccrop",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_crop_species_relink_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_crop_species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_crop_relinks_to",
                        to="crops.cropspecies",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("public_crop",),
                        name="unique_pending_public_crop_species_relink",
                    )
                ],
            },
        ),
    ]
