# Generated by Django 5.2.17 on 2026-09-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0107_public_crop_species_relink_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccropspeciesrelinkrequest',
            name='to_variety',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
