# Generated by Django 5.2.17 on 2026-09-24 09:14

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_provenance(apps, schema_editor):
    """Every crop currently linked to or imported from an entry derives from it.

    Uses the unfiltered model manager, so soft-deleted crops keep their
    provenance too.
    """
    Crop = apps.get_model('farm', 'Crop')
    Crop._base_manager.filter(
        source_public_crop__isnull=False,
        derived_from_public_crop__isnull=True,
    ).update(derived_from_public_crop=F('source_public_crop'))


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0108_publiccropspeciesrelinkrequest_to_variety"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="derived_from_public_crop",
            field=models.ForeignKey(
                blank=True,
                help_text="Provenance: the public entry this crop was imported from or linked to. Kept when the library link is removed, since values taken from the library remain CC BY-SA data.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_crops",
                to="farm.publiccrop",
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="source_public_crop",
            field=models.ForeignKey(
                blank=True,
                help_text="Library sync link: the public entry this crop pulls updates from and pushes changes to. Cleared by an unlink; provenance lives in derived_from_public_crop.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_crops",
                to="farm.publiccrop",
            ),
        ),
        migrations.RunPython(backfill_provenance, migrations.RunPython.noop),
    ]
