# Generated by Django 5.2.17 on 2026-10-03 04:46

from datetime import timedelta

from django.db import migrations, models
from django.db.models import Max

# Snapshot of farm.services.demo_project.DEMO_PROJECT_DESCRIPTIONS at the
# time of this migration.
DEMO_PROJECT_DESCRIPTIONS = (
    "Pers\u00f6nliches Demo-Projekt mit realistischen Beispieldaten.",
    "Personal demo project with realistic sample data.",
    "Reproduzierbares Demo-Projekt f\u00fcr Produkt-Screenshots.",
    "Reproducible demo project for product screenshots.",
)
# Seeding a demo project takes a few seconds; crop revisions written this
# soon after creation are taken to be the seed's own.
SEED_WINDOW = timedelta(minutes=2)


def backfill_demo_seeded_at(apps, schema_editor):
    """Estimate the seeding end for demo projects created before the marker.

    Seeding writes one "created" crop revision per crop and no other
    revisions, so the last of those within the seed window marks its end.
    """
    Project = apps.get_model("farm", "Project")
    EntityRevision = apps.get_model("farm", "EntityRevision")
    for project in Project.objects.filter(description__in=DEMO_PROJECT_DESCRIPTIONS).only("pk", "created_at"):
        seed_end = EntityRevision.objects.filter(
            project_id=project.pk,
            entity_type="crop",
            action="created",
            created_at__lte=project.created_at + SEED_WINDOW,
        ).aggregate(seed_end=Max("created_at"))["seed_end"]
        Project.objects.filter(pk=project.pk).update(demo_seeded_at=seed_end or project.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0110_repair_implicit_general_kultur_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demo_seeded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the demo template finished filling this project; empty for projects not created from the demo template. Seeding records revisions of its own, so only revisions after this point are user changes.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_demo_seeded_at, migrations.RunPython.noop),
    ]
