# Generated by Django 5.2.17 on 2026-10-02 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0017_crop_species_trigram_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropLibraryApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label chosen by the owner', max_length=120)),
                ('scope', models.CharField(choices=[('read', 'Read only'), ('write', 'Read and write')], default='read', max_length=20)),
                ('token_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(editable=False, help_text='Non-secret leading characters used to identify the token in listings', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_library_api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop library API token',
                'verbose_name_plural': 'Crop library API tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
